# Generated by Django 5.1.2 on 2024-11-04 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero_seleccionado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('comentarios', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
