# Generated by Django 5.2.7 on 2025-10-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.cliente'),
        ),
    ]
