# Generated by Django 5.1.2 on 2024-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filepath', models.CharField(max_length=255)),
            ],
        ),
    ]
