# Generated by Django 5.1.2 on 2024-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='filepath',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
