# Generated by Django 5.2.7 on 2025-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0002_alter_personas_cliente_alter_producto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dominio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
