# Generated by Django 5.2.7 on 2025-10-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0003_cliente_activo_cliente_descripcion_cliente_dominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='descripcion',
        ),
    ]
