# Generated by Django 5.1.2 on 2024-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0003_alter_producto_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='filepath',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
