# Generated by Django 5.2.7 on 2025-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0004_remove_personas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncliente',
            name='horas_extension_countdown',
            field=models.IntegerField(default=0),
        ),
    ]
