# Generated by Django 5.2.7 on 2025-10-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0005_alter_configuracioncliente_horas_extension_countdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteo',
            name='admin',
        ),
    ]
