# Generated by Django 5.1.2 on 2025-10-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0006_cliente_personas_cliente_producto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_final_countdown', models.DateTimeField(blank=True, null=True)),
                ('horas_extension_countdown', models.IntegerField(default=2)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('logo_base64', models.TextField(blank=True, null=True)),
                ('color_principal', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_secundario', models.CharField(default='#000000', max_length=7)),
                ('mostrar_boton_demo', models.BooleanField(default=True)),
                ('texto_boton_demo', models.CharField(default='Modo Demo', max_length=50)),
                ('auto_girar_ruleta', models.BooleanField(default=False)),
                ('intervalo_auto_girar', models.IntegerField(default=60)),
                ('texto_countdown', models.CharField(default='Empezamos la cuenta atras. Gracias por la paciencia...', max_length=200)),
                ('texto_ganador', models.CharField(default='La ganadora o el Ganador es', max_length=200)),
                ('texto_intentar_otra_vez', models.CharField(default='Vuelve a probar otra vez. Sin número asignado.', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='loteria.cliente')),
            ],
        ),
    ]
